# Generated by Django 2.0.2 on 2019-04-17 06:24

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('1', 'customer'), ('2', 'partner'), ('3', 'sponsor')], default='1', max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=user_profile.models.content_file_name)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
